// <auto-generated />
using Ambica.Services.ProductApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ambica.Services.ProductApi.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20241101045428_addingdata")]
    partial class addingdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ambica.Services.ProductApi.model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1112,
                            Availability = true,
                            Name = "Mirchi Powder",
                            Price = 250m,
                            Quantity = 500
                        },
                        new
                        {
                            Id = 1113,
                            Availability = true,
                            Name = "Dhania Powder",
                            Price = 50m,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 1114,
                            Availability = true,
                            Name = "Masala Kharam",
                            Price = 180m,
                            Quantity = 500
                        },
                        new
                        {
                            Id = 1115,
                            Availability = true,
                            Name = "Haldi Powder",
                            Price = 180m,
                            Quantity = 500
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
